export const rolesList = [
  {
    id: 'developer',
    subRoles: {
      frontend: ['prototyping', 'spa', 'crossBrowser'],
      backend: [
        'api',
        'database',
        'serverLogic',
        'serviceIntegration',
        'serverScaling',
        'serverArchitecture',
      ],
      fullStack: [
        'fullCycle',
        'webApplications',
        'frontendBackendIntegration',
        'quickMvp',
        'applicationSecurity',
      ],
      mobileDeveloper: [
        'mobileApp',
        'uiAdaptation',
        'crossPlatform',
        'rapidPrototyping',
        'performanceOptimization',
        'iosAndroid',
      ],
      gameDeveloper: [
        'gameLogic',
        'gameWorld',
        'gameMechanic',
        'gamePrototyping',
        'gameOptimization',
        'aiIntegration',
      ],
      embeddedDeveloper: [
        'firmware',
        'microcontroller',
        'iotDevice',
        'hardwareIntegration',
        'embeddedSystem',
        'hardwarePerformance',
      ],
    },
  },
  {
    id: 'designer',
    subRoles: {
      uiUx: [
        'interface',
        'userResearch',
        'uxAnalysis',
        'prototypeTesting',
        'usabilityImprovement',
        'userJourney',
      ],
      graphic: [
        'visualStyle',
        'logo',
        'illustrations',
        'marketingMockups',
        'brandbook',
        'presentation',
      ],
      motion: [
        'animations',
        'promoVideos',
        'socialMedia',
        'dynamicGraphics',
        'interfaceAnimations',
        'interactiveElements',
      ],
      '3d': [
        '3dModeling',
        'rendering',
        'texturing',
        '3dAsset',
        '3dAnimations',
        'productVisualization',
      ],
    },
  },
  {
    id: 'qa',
    services: [
      'manualTesting',
      'testCaseDesign',
      'defectTracking',
      'qualityAssurance',
      'functionalTesting',
      'regressionTesting',
      'bugReporting',
      'testExecution',
      'userAcceptance',
      'performanceTesting',
      'compatibilityTesting',
      'securityTesting',
      'testAutomation',
      'scriptingTestCases',
      'continuousIntegration',
      'testFramework',
      'automatedRegression',
      'performanceTestingAutomation',
    ],
  },
  {
    id: 'productManager',
    services: [
      'userNeeds',
      'ideaValidation',
      'mvpCreation',
      'marketAnalysis',
      'userInterviews',
      'productStrategy',
      'productLaunch',
      'postLaunchSupport',
    ],
  },
  {
    id: 'analyst',
    subRoles: {
      dataAnalyst: [
        'dataAnalysis',
        'dataVisualization',
        'reportGeneration',
        'dataDrivenDecision',
        'dataModeling',
        'userBehavior',
      ],
      businessAnalyst: [
        'marketResearch',
        'requirementAnalysis',
        'businessIdea',
        'processImprovement',
        'businessModel',
        'businessDocumentation',
      ],
      financialAnalyst: [
        'financialPlanning',
        'budgeting',
        'investmentEvaluation',
        'financialReport',
        'cashFlow',
        'profitabilityAssessment',
      ],
    },
  },
  {
    id: 'entrepreneur',
    subRoles: {
      startupFounder: [
        'startupIdeas',
        'conceptValidation',
        'teamBuilding',
        'mvpLaunch',
        'fundraising',
        'strategicPlanning',
      ],
      investor: [
        'projectFunding',
        'mentorship',
        'startupEvaluation',
        'networking',
        'investmentStrategy',
        'growthSupport',
      ],
      businessConsultant: [
        'strategicPlanning',
        'businessOptimization',
        'productDevelopment',
        'marketingSales',
        'businessProcess',
        'marketOpportunity',
      ],
    },
  },
  {
    id: 'marketer',
    services: [
      'socialMediaPromotion',
      'contentMarketing',
      'seoOptimization',
      'onlineAdvertising',
      'marketingAnalytics',
      'marketingStrategy',
    ],
  },
  {
    id: 'contentCreator',
    subRoles: {
      copywriter: [
        'contentWriting',
        'blogContent',
        'landingPage',
        'socialMedia',
        'videoScript',
        'seoCopywriting',
      ],
      mediaContent: [
        'photographyVideography',
        'socialMediaContent',
        'contentManagement',
        'contentStrategy',
        'visualStorytelling',
      ],
      smmManager: [
        'socialMediaManagement',
        'communityBuilding',
        'contentPlanning',
        'audienceEngagement',
        'targetedAdvertising',
        'socialMediaCrisis',
      ],
    },
  },
];
